import PDFDocument from "pdfkit";
import { getActor, jsonError } from "@/lib/api-helpers";
import { computePassport, consistencyLabel } from "@/lib/passport";
import { formatZAR } from "@/lib/utils";
import { logAudit } from "@/lib/audit";

export const runtime = "nodejs";

const BRAND = "#0f766e";
const DARK = "#0f172a";
const MUTED = "#64748b";

export async function GET() {
  const actor = await getActor();
  if (!actor || actor.role !== "trader") return jsonError("Unauthorized", 401);

  const passport = await computePassport(actor.sub, 180);

  const doc = new PDFDocument({ size: "A4", margin: 48 });
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))));

  // Header
  doc.rect(0, 0, doc.page.width, 96).fill(BRAND);
  doc.fillColor("#ffffff").fontSize(22).font("Helvetica-Bold").text("TradePulse", 48, 30);
  doc.fontSize(11).font("Helvetica").text("Business Readiness Passport", 48, 58);
  doc.fillColor(DARK).fontSize(18).font("Helvetica-Bold").text(passport.businessName, 48, 120);

  doc.fontSize(10).font("Helvetica").fillColor(MUTED);
  doc.text(`${passport.ownerName}  •  ${passport.businessType}  •  ${passport.location}`, 48, 144);
  doc.text(passport.sinceLabel, 48, 160);

  // Metrics block
  const metrics: [string, string][] = [
    ["Total revenue (6 months)", formatZAR(passport.totalRevenue)],
    ["Avg. monthly revenue", formatZAR(passport.avgMonthlyRevenue)],
    ["Transactions recorded", String(passport.totalTransactions)],
    ["Trading consistency", `${passport.consistencyScore}% (${consistencyLabel(passport.consistencyScore)})`],
    ["Revenue trend", passport.revenueTrend === "up" ? "Growing" : passport.revenueTrend === "down" ? "Declining" : "Stable"],
    ["Active trading days", String(passport.activeDays)],
  ];

  const startY = 190;
  metrics.forEach(([label, value], i) => {
    const y = startY + i * 34;
    doc.roundedRect(48, y, 499, 28, 5).fill(i % 2 === 0 ? "#f1f5f9" : "#f8fafc");
    doc.fillColor(MUTED).fontSize(10).font("Helvetica").text(label, 60, y + 9);
    doc.fillColor(DARK).font("Helvetica-Bold").text(value, 320, y + 9, { width: 210, align: "right" });
  });

  // Best sellers
  let y = startY + metrics.length * 34 + 20;
  doc.fillColor(BRAND).fontSize(13).font("Helvetica-Bold").text("Top selling products", 48, y);
  y += 22;
  doc.fontSize(10).font("Helvetica").fillColor(DARK);
  if (passport.bestSelling.length === 0) {
    doc.fillColor(MUTED).text("No sales recorded yet.", 48, y);
  } else {
    passport.bestSelling.forEach((p) => {
      doc.fillColor(DARK).font("Helvetica-Bold").text(p.productName, 48, y, { width: 260 });
      doc.font("Helvetica").fillColor(MUTED).text(`${p.units} units`, 320, y, { width: 100 });
      doc.fillColor(DARK).text(formatZAR(p.revenue), 420, y, { width: 127, align: "right" });
      y += 18;
    });
  }

  // Stock turnover
  y += 20;
  doc.fillColor(BRAND).fontSize(13).font("Helvetica-Bold").text("Stock turnover", 48, y);
  y += 22;
  if (passport.stockTurnover.length === 0) {
    doc.fontSize(10).font("Helvetica").fillColor(MUTED).text("Not enough stock data yet.", 48, y);
  } else {
    passport.stockTurnover.forEach((s) => {
      doc.fillColor(DARK).font("Helvetica-Bold").fontSize(10).text(s.productName, 48, y, { width: 260 });
      doc.font("Helvetica").fillColor(MUTED).text(`${s.turnover}x / month (${s.note})`, 320, y, { width: 227, align: "right" });
      y += 18;
    });
  }

  // Footer
  doc
    .fillColor(MUTED)
    .fontSize(8)
    .font("Helvetica")
    .text(
      `Generated by TradePulse on ${passport.generatedAt.toLocaleString("en-ZA")}. This passport is generated from transaction records captured by the trader and is shared only with the trader's consent. Not a formal financial statement or credit report.`,
      48,
      doc.page.height - 80,
      { width: 499 }
    );

  doc.end();
  const pdf = await done;

  void logAudit(actor, "passport.generated", { entity: "ReadinessSnapshot" });

  return new Response(new Uint8Array(pdf), {
    headers: {
      "content-type": "application/pdf",
      "content-disposition": `attachment; filename="TradePulse-Passport-${passport.businessName.replace(
        /[^a-z0-9]+/gi,
        "-"
      )}.pdf"`,
    },
  });
}